### ISSUE TITLE
Oscar fails to precompile on Ubuntu

### ISSUE THREAD

**Issue by wbhart** [oscar-system/Oscar.jl#137]
I had a previous unsuccessful build of Oscar due to g++ being missing on my machine. So I removed Oscar (Pkg.rm) then the following happened:

```
(v1.3) pkg> add Oscar
 Resolving package versions...
  Updating `~/.julia/environments/v1.3/Project.toml`
  [f1435218] + Oscar v0.2.0
  Updating `~/.julia/environments/v1.3/Manifest.toml`
  [9e28174c] + BinDeps v1.0.1
  [631607c0] + CMake v1.2.0
  [1f15a43c] + CxxWrap v0.9.1
  [3e1990a7] + Hecke v0.8.4
  [682c06a0] + JSON v0.21.0
  [1914dd2f] + MacroTools v0.5.5
  [f1435218] + Oscar v0.2.0
  [69de0a69] + Parsers v1.0.7
  [d720cf60] + Polymake v0.3.0
  [ae029012] + Requires v1.0.1
  [bcd08a7b] + Singular v0.2.2
  [30578b45] + URIParser v0.4.1
  [a63ad114] + Mmap
  [9abbd945] + Profile
  [10745b16] + Statistics

(v1.3) pkg> build Oscar
  Building CxxWrap ──→ `~/.julia/packages/CxxWrap/hEmjg/deps/build.log`
  Building CMake ────→ `~/.julia/packages/CMake/ULbyn/deps/build.log`
  Building Polymake ─→ `~/.julia/packages/Polymake/MuMBQ/deps/build.log`
  Building LoadFlint → `~/.julia/packages/LoadFlint/jHlQx/deps/build.log`
  Building Nemo ─────→ `~/.julia/dev/Nemo/deps/build.log`
 Resolving package versions...
  Building Singular ─→ `~/.julia/packages/Singular/GsN0h/deps/build.log`
 Resolving package versions...

julia> using Oscar
[ Info: Precompiling Oscar [f1435218-dba5-11e9-1e4d-f1a5fab5fc13]
ERROR: LoadError: could not load library "/home/wbhart/.julia/packages/Polymake/MuMBQ/src/../deps/src/libpolymake.so"
/home/wbhart/julia-1.3.1/bin/../lib/julia/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /home/wbhart/.julia/packages/Polymake/MuMBQ/src/../deps/src/libpolymake.so)
Stacktrace:
 [1] #dlopen#3(::Bool, ::typeof(Libdl.dlopen), ::String, ::UInt32) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.3/Libdl/src/Libdl.jl:109
 [2] dlopen at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.3/Libdl/src/Libdl.jl:109 [inlined]
 [3] readmodule(::String, ::Symbol, ::Module, ::Nothing) at /home/wbhart/.julia/packages/CxxWrap/hEmjg/src/CxxWrap.jl:669
 [4] wrapmodule(::String, ::Symbol, ::Module, ::Nothing) at /home/wbhart/.julia/packages/CxxWrap/hEmjg/src/CxxWrap.jl:676
 [5] top-level scope at /home/wbhart/.julia/packages/Polymake/MuMBQ/src/Polymake.jl:37
 [6] include at ./boot.jl:328 [inlined]
 [7] include_relative(::Module, ::String) at ./loading.jl:1105
 [8] include(::Module, ::String) at ./Base.jl:31
 [9] top-level scope at none:2
 [10] eval at ./boot.jl:330 [inlined]
 [11] eval(::Expr) at ./client.jl:425
 [12] top-level scope at ./none:3
in expression starting at /home/wbhart/.julia/packages/Polymake/MuMBQ/src/Polymake.jl:37
ERROR: LoadError: Failed to precompile Polymake [d720cf60-89b5-51f5-aff5-213f193123e7] to /home/wbhart/.julia/compiled/v1.3/Polymake/QizyK_e1zOn.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at ./loading.jl:1283
 [3] _require(::Base.PkgId) at ./loading.jl:1024
 [4] require(::Base.PkgId) at ./loading.jl:922
 [5] require(::Module, ::Symbol) at ./loading.jl:917
 [6] include at ./boot.jl:328 [inlined]
 [7] include_relative(::Module, ::String) at ./loading.jl:1105
 [8] include(::Module, ::String) at ./Base.jl:31
 [9] top-level scope at none:2
 [10] eval at ./boot.jl:330 [inlined]
 [11] eval(::Expr) at ./client.jl:425
 [12] top-level scope at ./none:3
in expression starting at /home/wbhart/.julia/packages/Oscar/kRdEf/src/Oscar.jl:33
ERROR: Failed to precompile Oscar [f1435218-dba5-11e9-1e4d-f1a5fab5fc13] to /home/wbhart/.julia/compiled/v1.3/Oscar/aJ3Pg_e1zOn.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at ./loading.jl:1283
 [3] _require(::Base.PkgId) at ./loading.jl:1024
 [4] require(::Base.PkgId) at ./loading.jl:922
 [5] require(::Module, ::Symbol) at ./loading.jl:917
```

GCC is version 9.3.0
Ubuntu is 20.04 LTS (the standard on Windows Subsystem for Linux)
CMake is 3.16.3
Julia is 1.3.1

**Comment by thofma** [comment]
Looks very familiar to https://github.com/oscar-system/Polymake.jl/issues/251, which was fixed in https://github.com/oscar-system/Polymake.jl/pull/252 and which is has been part of Polymake.jl since version v0.3.3. The latest OSCAR version (v0.4) requires Polymake.jl >= v0.4, but for some reason for you the package manager is adding OSCAR v0.2. You should probably free Nemo and do an `update` to get the latest version and not some broken old version.

**Comment by wbhart** [comment]
I know this is probably a stupid question, but why does using a later version of Nemo mean an earlier version of Oscar. I had Nemo dev'd for a talk I was going to give (about Oscar/Nemo/AbstractAlgebra).

[The talk didn't happen, for this and other personal reasons.]

**Comment by thofma** [comment]
Can you try a `resolve` or `update`?

**Comment by wbhart** [comment]
I think we should remove the broken Oscar release. It's embarrassing that it's the one that gets picked in situations like this.

**Comment by wbhart** [comment]
No change with resolve or update. I don't think it is a dependency issue. It's not the Julia package system complaining, it's the precompiler.

**Comment by thofma** [comment]
What do you mean? I told you that you have an old Oscar.jl/Polymake.jl pulled in because your dev'ed Nemo version is holding back an update. The issue is https://github.com/oscar-system/Polymake.jl/issues/251 and has been fixed in https://github.com/oscar-system/Polymake.jl/pull/252.

Try `free Nemo` and `update`.

PS: One cannot delete releases.

**Comment by wbhart** [comment]
Can't we use semver somehow to add a new release on that branch of the release tree that doesn't have any valid compatible versions of Polymake.jl or something, so that at least you get a message from the package system instead of the precompiler when this happens?

**Comment by thofma** [comment]
> Can't we use semver somehow to add a new release on that branch of the release tree that doesn't have any valid compatible versions of Polymake.jl or something,

But then the package manager won't pick this version, because he tries to resolve these kind of issues (that we are trying to introduce artificially).

Not sure how important it is though. I don't think a new user will ever see them, nor someone who has not dev'ed some package. The premise of the package manager is that if you dev stuff, you are on your own :-/

**Comment by wbhart** [comment]
The whole intention of it would be to stop it picking the broken release. I don't mind if it tries to resolve the issue (it should fail to do so). It's just that it would have given me a hint as to what was wrong, instead of making me think that Oscar was currently broken.

**Comment by thofma** [comment]
How can the resolver fail to find incompatible versions? If we add versions that are incompatible on purpose, he will return any combination of versions that are compatible, which would probably be the one that you encountered in your setup.

**Comment by wbhart** [comment]
Yeah, so that wouldn't work then.

Well, I don't know how to fix it. It's really annoying that we can't dev our packages independently.

For now I've just removed Oscar, as I need to dev Nemo.

**Comment by wbhart** [comment]
We've probably discussed this before, sorry if that's the case, but I don't remember.

Would the following work:

Every time we do a release of a package X, say version 18.7, immediately change the version in master to 18.8-dev.

Then all packages Y that can have package X 18.7 as a dependency would just need an upper bound of 18.8 *non-inclusive* for package X in [compat], and we could then dev package X and package Y would still be ok with it.

**Comment by thofma** [comment]
I am not sure I understand. If your local `X` is dev'ed and at `18.8-dev` and `Y` has an upper bound of `18.8` non-inclusive, then the package manager will throw a conflict. The version of `X` is fixed (to `18.8-dev` and since it is dev'ed) and there does not exist a version of `Y` which allows such a version of `X` in its compat section.

(I think the original problem that you posted is related to the fact that with binary dependencies there are more compatability layers, e.g. the Ubuntu version, which are not and cannot possibly be taking into account by the package manager. So trying to fix them using the package manager will probably not work.)

**Comment by wbhart** [comment]
Isn't 18.8-dev < 18.8 ?

If not, then I guess I mean 18.7-dev. But I find it odd that a dev version would come after an official release.

**Comment by thofma** [comment]
Ah yes sorry, you are right. But then I dont see the difference between keeping the version in the master branch of `X` at  `18.7` (which we are doing at the moment) and changing it to `18.8-dev`. Both are compatible with exactly the same versions of `Y`?

**Comment by wbhart** [comment]
Well then I don't understand why I had the problem I did. Why would the only version of Polymake which supports the most recent version of Nemo be an old, broken one and not a recent one?

I dev'd Nemo just a few hours before I tried to build Oscar. I can still see it in the traceback in my console!

**Comment by thofma** [comment]
Not sure why it happened. What is the output of `Pkg.status()`?

**Comment by wbhart** [comment]
```
julia> Pkg.status()
    Status `~/.julia/environments/v1.3/Project.toml`
  [c3fe647b] AbstractAlgebra v0.9.2 [`~/.julia/dev/AbstractAlgebra`]
  [2edaba10] Nemo v0.17.6 [`~/.julia/dev/Nemo`]
```

Of course I have temporarily removed Oscar, since it didn't work anyway.

**Comment by wbhart** [comment]
Nemo tells me:

```
Welcome to Nemo version 0.17.6-dev
```

**Comment by wbhart** [comment]
And it is a fresh install of Ubuntu 20.04. The only other thing I have on the system (apart from latex and so on) is a flint2 directory, where I've been maintaining Flint.

**Comment by thofma** [comment]
Weird. Can you try `free Nemo` and `free AbstractAlgebra`, followed by `add Oscar`? The freeing should not touch `dev` directories, but restores it to a stable version.

**Comment by wbhart** [comment]
I'll try it later today and let you know. Right now I am working on some AbstractAlgebra code before the meeting today.

**Comment by fingolfin** [comment]
I've had several weird issues with Pkg, and frankly, I think it's not our fault, I blame Pkg. Like, that when you do `add Oscar`, if it decides to not install the latest version, IMHO it should print a big warning: "Warning, installing Oscar.jl 0.2.0 instead of the latest version 0.4.0 because REASON". (see also https://github.com/JuliaLang/Pkg.jl/issues/1655, which I submitted in February; look at how many people are commenting there with the same or similar issues).

I've also seen it seemingly randomly downgrade things when I run a `Pkg.update()` -- like, it switched to a slightly older Nemo and downgraded LoadFlint, and I have no idea *why* it suddenly did that.

So, really, I don't think we can do much if anything about this (well, other than perhaps submitting patches to Pkg.jl ;-)).

**Comment by wbhart** [comment]
@thofma Sorry I didn't get to this today. I got distracted by other work related stuff and didn't even finish my sqrt implementation.

I will get back to it on Monday. I will still do the Flint release though, as I now have approval from @tthsqe12 and @fredrik-johansson

**Comment by thofma** [comment]
No worries, it is not urgent.

**Comment by wbhart** [comment]
@fingolfin I agree that Pkg is flaky, but this is entirely repeatable. Either there is a bug in Pkg which we should report, or there is a bug in the way we are using semver.

I have AbstractAlgebra and Nemo dev'd on a fresh install of Julia 1.3.1 on a fresh install of Ubuntu 20.04.

It's not causing any major problem for me personally at the moment, as I do not currently have any need of Oscar whilst I am working on Nemo and AbstractAlgebra. But that's just me and that's just now.

As a further data point it also chooses Polymake 0.3.0 if I just add Polymake and not Oscar. 

```
(v1.3) pkg> add Polymake
 Resolving package versions...
  Updating `~/.julia/environments/v1.3/Project.toml`
  [d720cf60] + Polymake v0.3.0
  Updating `~/.julia/environments/v1.3/Manifest.toml`
  [9e28174c] + BinDeps v1.0.1
  [631607c0] + CMake v1.2.0
  [1f15a43c] + CxxWrap v0.9.1
  [682c06a0] + JSON v0.21.0
  [1914dd2f] + MacroTools v0.5.5
  [69de0a69] + Parsers v1.0.7
  [d720cf60] + Polymake v0.3.0
  [30578b45] + URIParser v0.4.1
  [a63ad114] + Mmap

(v1.3) pkg> build Polymake
  Building CxxWrap ─→ `~/.julia/packages/CxxWrap/hEmjg/deps/build.log`
  Building CMake ───→ `~/.julia/packages/CMake/ULbyn/deps/build.log`
  Building Polymake → `~/.julia/packages/Polymake/MuMBQ/deps/build.log`

julia> using Polymake
[ Info: Precompiling Polymake [d720cf60-89b5-51f5-aff5-213f193123e7]
ERROR: LoadError: could not load library "/home/wbhart/.julia/packages/Polymake/MuMBQ/src/../deps/src/libpolymake.so"
/home/wbhart/julia-1.3.1/bin/../lib/julia/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /home/wbhart/.julia/packages/Polymake/MuMBQ/src/../deps/src/libpolymake.so)
Stacktrace:
 [1] #dlopen#3(::Bool, ::typeof(Libdl.dlopen), ::String, ::UInt32) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.3/Libdl/src/Libdl.jl:109
 [2] dlopen at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.3/Libdl/src/Libdl.jl:109 [inlined]
 [3] readmodule(::String, ::Symbol, ::Module, ::Nothing) at /home/wbhart/.julia/packages/CxxWrap/hEmjg/src/CxxWrap.jl:669
 [4] wrapmodule(::String, ::Symbol, ::Module, ::Nothing) at /home/wbhart/.julia/packages/CxxWrap/hEmjg/src/CxxWrap.jl:676
 [5] top-level scope at /home/wbhart/.julia/packages/Polymake/MuMBQ/src/Polymake.jl:37
 [6] include at ./boot.jl:328 [inlined]
 [7] include_relative(::Module, ::String) at ./loading.jl:1105
 [8] include(::Module, ::String) at ./Base.jl:31
 [9] top-level scope at none:2
 [10] eval at ./boot.jl:330 [inlined]
 [11] eval(::Expr) at ./client.jl:425
 [12] top-level scope at ./none:3
in expression starting at /home/wbhart/.julia/packages/Polymake/MuMBQ/src/Polymake.jl:37
ERROR: Failed to precompile Polymake [d720cf60-89b5-51f5-aff5-213f193123e7] to /home/wbhart/.julia/compiled/v1.3/Polymake/QizyK_e1zOn.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at ./loading.jl:1283
 [3] _require(::Base.PkgId) at ./loading.jl:1024
 [4] require(::Base.PkgId) at ./loading.jl:922
 [5] require(::Module, ::Symbol) at ./loading.jl:917
```

It ought to be possible to figure out which dependency is incorrect, and if not to find a way to reproduce the problem reliably and report it. I will work on narrowing it down further.

**Comment by thofma** [comment]
Can you do a `add Polymake@0.4.0` or something like that? Or `pin Polymake@0.4.0`.

**Comment by thofma** [comment]
Ah, the problem is `BinaryProvider`. Polymake wants >=0.5.3, where as we pinned it to [0.4 - 0.5) in Nemo (not sure if we still need this).

**Comment by thofma** [comment]
Can you change in the Nemo Project.toml the BinaryProvider version to ^0.5.3 and try again?

**Comment by wbhart** [comment]
That's one of a number of problems. The reason it picks Polymake 0.3.0 is that in the latest Nemo we want LoadFlint 0.2.1. The last version of Polymake that did not demand a version 0.1 of LoadFlint or a specific Nemo was 0.3.0. 

So currently, this must be a problem for everyone, not just me.

**Comment by thofma** [comment]
Polymake master branch is on LoadFlint ^0.2.1. We could ask them for a new tag. @benlorenz @kalmarek (if you are not the right people to ping, sorry!)

**Comment by wbhart** [comment]
I think the issue is we are using Julia semver incorrectly. Note from the Pkg manual:

```
^0.2.3 = [0.2.3, 0.3.0)
```

NOT

```
^0.2.3 = [0.2.3, 1.0.0)
```

as one might expect. However:

```
^1.2.3 = [1.2.3, 2.0.0)
```

NOT

```
^1.2.3 = [1.2.3, 1.3.0)
```

**Comment by thofma** [comment]
Yes, I think we used `^0.2.3` because we thought it means `[0.2.3, 0.3.0)` (we consider `0.3` breaking). Where are we not using it in this way?

**Comment by wbhart** [comment]
The reason for this is that version 0.x.y is considered an initial development release, not a public release. Anything MAY change at any time. 1.0.0 is the first public release after which the normal rules apply.

**Comment by thofma** [comment]
Anything? I don't think so. Increasing just the patch number is considered non-breaking, e.g., 0.2.1 is not allowed to brake stuff that worked with 0.2.0.

Where are we using it incorrectly?

**Comment by wbhart** [comment]
Well, we may have intended it, but it means we have to use versioning differently if we want to keep things in sync for development purposes.

Anyhow, let's just fix the issue and we can monitor our versioning more carefully going forward now that we are aware of it.

**Comment by wbhart** [comment]
Yes, anything. From semver:

```
Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.
```

**Comment by thofma** [comment]
When you say we have to use versioning differently, can you point to a place where it needs to be fixed? Nemo/AA/Hecke follow the principle that 0.x.y -> 0.x.y+1 is not breaking. All the breaking stuff happens in 0.x.y -> 0.x+1.0.

**Comment by kalmarek** [comment]
@thofma @wbhart what version should `LoadFlint` point to?

btw. my best experience is to use julia environments for development; trying to `dev` anything in global one (i.e. `v1.3`) is asking for trouble. you can start by `dev Nemo` (which clones it to `~/.julia/dev`; you can just symlink your local dev copy), then `free Nemo` to have the released version in `1.3`; If you need to devel, just `julia --project=~/.julia/dev/Nemo`

**Comment by thofma** [comment]
That latest released version of Polymake points to LoadFlint ^0.1, but your master (and Nemo for a while) point to ^0.2.1.

**Comment by wbhart** [comment]
Yes, ^0.2.1 will work (until we switch to 0.3.0). They all need to be updated in sync until we reach 1.0.0. Only then are minor versions considered backwards compatible.

**Comment by wbhart** [comment]
As for Nemo, we should update BinaryProvider I guess, if we still need it at all (I don't know its relation to these jll thingys).

**Comment by wbhart** [comment]
@thofma You are right that Julia considers the patch increment to be backwards compatible. I don't know why semver words its rules the way it does in comparison.

**Comment by thofma** [comment]
It is not super clear. They cite semver.org in the documentation, but clearly don't follow it for 0.x.y. I will bump the BinaryProvider version together with the flint version bump. I am currently working on it.

**Comment by thofma** [comment]
Sorry julia people, it is at the top at https://julialang.github.io/Pkg.jl/v1/compatibility/#compat-pre-1.0-1

**Comment by wbhart** [comment]
Ah, that explains it @thofma 

So now we are up to speed on this incredible convoluted set of rules. :-)

**Comment by wbhart** [comment]
By the way, I notice that loadflint is not in Singular.jl's compat. I don't know if that is or isn't a good thing. But if you can let me know, I can report it there if necessary.

**Comment by thofma** [comment]
Probably at some time once Singular switches over to use flint only and they need some fix that Dan added/fixed recently. But I am not sure.

P.S.: We have BinaryProvider 0.5, which is, ^0.5, which should be compatible with whatever Polymake.jl wants.

**Comment by wbhart** [comment]
@thofma Yes, it is. So no problem there.
