### ISSUE TITLE
Book test sometimes timeout (bad random seed?)

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/Oscar.jl#4493]
I noticed that sometimes our booktests timeout after 2.5 hours / 150 minutes, e.g. [here](https://github.com/oscar-system/Oscar.jl/actions/runs/12918483264/job/36027096353?pr=4490) for PR #4490 while usually they finish with lots of room to spare; e.g. [here in 40 minutes](https://github.com/oscar-system/Oscar.jl/actions/runs/12921551561/job/36035783679).

In this case, the last message from the test runner in the logs before a gazillion messages of the form `From worker 7:	GC: pause 15.33ms. collected 52.249626MB. incr` was this:
```
2025-01-22T23:08:56.8299319Z       From worker 7:	    vinberg_2.jlcon
```
Not having looked at when this filename is printed, I don't know if this indicates we are running the tests in `vinberg_2.jlcon`, or perhaps in the file after it.

But anyway, my suspicion is that there are some tests here which "usually" work but for some RNG seed states end up performing much worse than usual.

Perhaps we should reduce fluctuation in this test by forcing a specific seed? Or do we already set a seed -- then this might a sign of another source of randomness we do not yet control for (e.g. when Singular is forking to achieve parallelism, I am guessing the order in which child processes finish their task may affect the overall result)

Also it may be useful if someone dug into it to figure out which part causes the issue. Since we parse the `.jlcon` files to process them step-by-step, perhaps we could enable a debug mode where it prints out which line (number) it is currently processing?

**Comment by benlorenz** [comment]
I have also noticed this, this has been happening for quite a while.

The filename is indeed printed directly before that jlcon is run.

We do set a fixed seed before every chapter:
https://github.com/oscar-system/Oscar.jl/blob/0cfe803d69a09932992195c34a5a1ca63822ba03/test/book/test.jl#L255
So in theory the runs should be deterministic. There are several chapters with random output where this does work as expected.

I can add a debug mode to print the executed lines.

**Comment by benlorenz** [comment]
Directly in the `run_repl_string` we can only print the whole jlcon file but not each input line, since we basically paste the whole jlcon file to the repl (in bracketed paste mode).

I started working on a PR to help debugging this by adding a hangcheck timer: #4504

And we did in fact hit exactly the relevant issue in this run:
https://github.com/oscar-system/Oscar.jl/actions/runs/12988216014/job/36218721340?pr=4504

But the hangcheck triggered only once after about 10 minutes, at `vinberg_2.jlcon` line 153, `julia> B = [basis_representation(Y2, D) for D in pullbackDivY1];`.
It did not trigger at all after this, so I would assume that we are either in some tight loop or in non-julia code which does not allow the timer to run again (somewhere after that line 153...).

**Comment by fingolfin** [comment]
Is there anything randomized in this vinberg example that could cause this, @simonbrandhorst @HechtiDerLachs ?

Although we also do reset the random seeds of all RNGs we know about, so this is still odd... perhaps there are still some RNGs we don't know about out?

@fieker speculates that there might be something deep in the number theory code...? (But it shouldn't matter for vinberg?)

And of course hash values can change if memory layouts change etc.

**Comment by HechtiDerLachs** [comment]
I just had the code run again and could not reproduce the error. My suspicion that some lattice theoretic code with randomized elements was responsible, was **not** confirmed. We only do computations in polynomial rings over the rationals and I do not see where any of such randomization comes from. Do we still have any stacktraces which reveal where exactly things are hanging?

**Comment by benlorenz** [comment]
It only happens infrequently and I don't have a backtrace for this. I tried to add a hangcheck timer, but the timer didn't trigger anymore even though it was clearly was stuck (e.g. https://github.com/oscar-system/Oscar.jl/actions/runs/12988216014/job/36218721340?pr=4504).
We would probably need to run the check in a separate process, I can give it another try soon.

**Comment by benlorenz** [comment]
I temporarily modified the code in #4504 such that the booktests run in the `:default` threadpool and the hangcheck runs in the `:interactive` one. I also changed the booktests to run only the fibration hopping chapter.
This does lead to some (probably unrelated) singular crashes [1] for julia 1.10 (maybe because it is now running on thread 2?).

But the hangcheck did run properly now and for the stuck jobs points to this line:
```
Hangcheck triggered:
 +65min Current file: specialized/brandhorst-zach-fibration-hopping/vinberg_2.jlcon
 +65min Current line: f3 = fibers[3][I]; representative(elliptic_parameter(Y1, f3))
```
https://github.com/oscar-system/Oscar.jl/actions/runs/14020138280/job/39250978343?pr=4504#step:8:95362
Warning: the log is quite long and might take a while to load, alternatively download the raw log and search for `Hangcheck`, searching for `User defined signal` should bring you to the backtraces.
There are several runs in my PR now which all point to that line.

Most of the time the backtrace unfortunately just looks like this:
```
signal (10): User defined signal 1
__gmpn_add_n_x86_64 at /opt/hostedtoolcache/julia/1.11.4/x64/bin/../lib/julia/libgmp.so.10 (unknown line)
unknown function (ip: (nil))
epoll_pwait at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
uv__io_poll at /workspace/srcdir/libuv/src/unix/linux.c:1404
uv_run at /workspace/srcdir/libuv/src/unix/core.c:430
ijl_task_get_next at /cache/build/builder-amdci5-5/julialang/julia-release-1-dot-11/src/scheduler.c:522
poptask at ./task.jl:1012
wait at ./task.jl:1021
#wait#731 at ./condition.jl:130
wait at ./condition.jl:125 [inlined]
_trywait at ./asyncevent.jl:145
#816 at ./asyncevent.jl:311
unknown function (ip: 0x7fc24b13807f)
jl_apply at /cache/build/builder-amdci5-5/julialang/julia-release-1-dot-11/src/julia.h:2157 [inlined]
start_task at /cache/build/builder-amdci5-5/julialang/julia-release-1-dot-11/src/task.c:1202
unknown function (ip: (nil))
```

But there are a few better ones:
```
FindLiveRangeReverse at /workspace/srcdir/gap-4.14.0/src/julia_gc.c:448 [inlined]
SafeScanTaskStack at /workspace/srcdir/gap-4.14.0/src/julia_gc.c:472
ScanTaskStack at /workspace/srcdir/gap-4.14.0/src/julia_gc.c:509 [inlined]
GapTaskScanner at /workspace/srcdir/gap-4.14.0/src/julia_gc.c:642
gc_mark_outrefs at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gc.c:2441 [inlined]
gc_queue_remset at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gc.c:2991 [inlined]
_jl_gc_collect at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gc.c:3217
ijl_gc_collect at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gc.c:3524
maybe_collect at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gc.c:937 [inlined]
ijl_gc_counted_malloc at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gc.c:3691
__gmpz_realloc at /home/oscarci-tester/oscar-runners/runner-04/_work/_tool/julia/1.10.9/x64/bin/../lib/julia/libgmp.so.10 (unknown line)
__gmpz_sub at /home/oscarci-tester/oscar-runners/runner-04/_work/_tool/julia/1.10.9/x64/bin/../lib/julia/libgmp.so.10 (unknown line)
_nlSub_aNoImm_OR_bNoImm(snumber*, snumber*) at /home/oscarci-tester/oscar-runners/runner-04/julia/artifacts/8f4444dc1ddba49118238e1595fd22f7047b7c05/lib/libpolys.so (unknown line)
p_Minus_mm_Mult_qq__FieldQ_LengthTwo_OrdPomogNeg(spolyrec*, spolyrec*, spolyrec*, int&, spolyrec*, ip_sring*) at /home/oscarci-tester/oscar-runners/runner-04/julia/artifacts/8f4444dc1ddba49118238e1595fd22f7047b7c05/lib/libpolys.so (unknown line)
kBucket_Minus_m_Mult_p(kBucket*, spolyrec*, spolyrec*, int*, spolyrec*) at /home/oscarci-tester/oscar-runners/runner-04/julia/artifacts/8f4444dc1ddba49118238e1595fd22f7047b7c05/lib/libpolys.so (unknown line)
ksReducePoly(sLObject*, sTObject*, spolyrec*, snumber**, spolyrec**, skStrategy*, int) at /home/oscarci-tester/oscar-runners/runner-04/julia/artifacts/8f4444dc1ddba49118238e1595fd22f7047b7c05/lib/libSingular.so (unknown line)
redtailBba(sLObject*, int, skStrategy*, int, int) at /home/oscarci-tester/oscar-runners/runner-04/julia/artifacts/8f4444dc1ddba49118238e1595fd22f7047b7c05/lib/libSingular.so (unknown line)
bba(sip_sideal*, sip_sideal*, intvec*, bigintmat*, skStrategy*) at /home/oscarci-tester/oscar-runners/runner-04/julia/artifacts/8f4444dc1ddba49118238e1595fd22f7047b7c05/lib/libSingular.so (unknown line)
kStd_internal(sip_sideal*, sip_sideal*, tHomog, intvec**, bigintmat*, int, int, intvec*, int (*)(skStrategy*)) at /home/oscarci-tester/oscar-runners/runner-04/julia/artifacts/8f4444dc1ddba49118238e1595fd22f7047b7c05/lib/libSingular.so (unknown line)
idQuot(sip_sideal*, sip_sideal*, int, int) at /home/oscarci-tester/oscar-runners/runner-04/julia/artifacts/8f4444dc1ddba49118238e1595fd22f7047b7c05/lib/libSingular.so (unknown line)
std::_Function_handler<sip_sideal* (sip_sideal*, sip_sideal*, bool, ip_sring*), singular_define_ideals(jlcxx::Module&)::{lambda(sip_sideal*, sip_sideal*, bool, ip_sring*)#11}>::_M_invoke(std::_Any_data const&, sip_sideal*&&, sip_sideal*&&, bool&&, ip_sring*&&) at /home/oscarci-tester/oscar-runners/runner-04/julia/artifacts/2af3954532f1b48f0f55af11f99a7f7cc512d3ca/lib/libsingular_julia.so (unknown line)
jlcxx::detail::CallFunctor<sip_sideal*, sip_sideal*, sip_sideal*, bool, ip_sring*>::apply(void const*, jlcxx::WrappedCppPtr, jlcxx::WrappedCppPtr, bool, jlcxx::WrappedCppPtr) at /home/oscarci-tester/oscar-runners/runner-04/julia/artifacts/2af3954532f1b48f0f55af11f99a7f7cc512d3ca/lib/libsingular_julia.so (unknown line)
id_Quotient at /home/oscarci-tester/oscar-runners/runner-04/julia/packages/CxxWrap/I0P2E/src/CxxWrap.jl:676 [inlined]
quotient at /home/oscarci-tester/oscar-runners/runner-04/julia/packages/Singular/sh9V0/src/ideal/ideal.jl:560
unknown function (ip: 0x7fd3869aab39)
_jl_invoke at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:2895 [inlined]
ijl_apply_generic at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:3077
quotient at /home/oscarci-tester/oscar-runners/runner-04/_work/Oscar.jl/Oscar.jl/src/Rings/mpoly-ideals.jl:295
#5718 at /home/oscarci-tester/oscar-runners/runner-04/_work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Sheaves/IdealSheaves.jl:877 [inlined]
_minimal_power_such_that at /home/oscarci-tester/oscar-runners/runner-04/_work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Sheaves/IdealSheaves.jl:800
unknown function (ip: 0x7fd38391831e)
_jl_invoke at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:2895 [inlined]
ijl_apply_generic at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:3077
#order_of_vanishing#5715 at /home/oscarci-tester/oscar-runners/runner-04/_work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Sheaves/IdealSheaves.jl:877
order_of_vanishing at /home/oscarci-tester/oscar-runners/runner-04/_work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Sheaves/IdealSheaves.jl:833
unknown function (ip: 0x7fd383916640)
_jl_invoke at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:2895 [inlined]
ijl_apply_generic at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:3077
#_subsystem#6086 at /home/oscarci-tester/oscar-runners/runner-04/_work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Divisors/WeilDivisor.jl:573
_jl_invoke at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:2895 [inlined]
ijl_apply_generic at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:3077
_subsystem at /home/oscarci-tester/oscar-runners/runner-04/_work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Divisors/WeilDivisor.jl:546
_jl_invoke at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:2895 [inlined]
ijl_apply_generic at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:3077
subsystem at /home/oscarci-tester/oscar-runners/runner-04/_work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Divisors/WeilDivisor.jl:530
_elliptic_parameter at /home/oscarci-tester/oscar-runners/runner-04/_work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Surfaces/EllipticSurface/NeighborStep.jl:419
unknown function (ip: 0x7fd383d9e21f)
_jl_invoke at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:2895 [inlined]
ijl_apply_generic at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:3077
elliptic_parameter at /home/oscarci-tester/oscar-runners/runner-04/_work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Surfaces/EllipticSurface/NeighborStep.jl:401
unknown function (ip: 0x7fd383d82dc9)
_jl_invoke at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:2895 [inlined]
ijl_apply_generic at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:3077
jl_apply at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/julia.h:1982 [inlined]
do_call at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/interpreter.c:126
eval_value at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/interpreter.c:223
eval_stmt_value at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/interpreter.c:174 [inlined]
eval_body at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/interpreter.c:617
jl_interpret_toplevel_thunk at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/interpreter.c:775
jl_toplevel_eval_flex at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/toplevel.c:934
jl_toplevel_eval_flex at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/toplevel.c:877
jl_toplevel_eval_flex at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/toplevel.c:877
ijl_toplevel_eval_in at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/toplevel.c:985
eval at ./boot.jl:385 [inlined]
eval_user_input at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/usr/share/julia/stdlib/v1.10/REPL/src/REPL.jl:150
repl_backend_loop at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/usr/share/julia/stdlib/v1.10/REPL/src/REPL.jl:246
#start_repl_backend#46 at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/usr/share/julia/stdlib/v1.10/REPL/src/REPL.jl:231
start_repl_backend at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/usr/share/julia/stdlib/v1.10/REPL/src/REPL.jl:228
_jl_invoke at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:2895 [inlined]
ijl_apply_generic at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:3077
#run_repl#59 at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/usr/share/julia/stdlib/v1.10/REPL/src/REPL.jl:389
run_repl at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/usr/share/julia/stdlib/v1.10/REPL/src/REPL.jl:375 [inlined]
run_repl at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/usr/share/julia/stdlib/v1.10/REPL/src/REPL.jl:375 [inlined]
#1 at /home/oscarci-tester/oscar-runners/runner-04/_work/Oscar.jl/Oscar.jl/test/book/test.jl:144
unknown function (ip: 0x7fd3a01d8e82)
_jl_invoke at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:2895 [inlined]
ijl_apply_generic at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:3077
jl_apply at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/julia.h:1982 [inlined]
start_task at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/task.c:1256
unknown function (ip: (nil))
unknown function (ip: 0x7fd3c77d0f14)
pthread_cond_wait at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
uv_cond_wait at /workspace/srcdir/libuv/src/unix/thread.c:883
jl_safepoint_wait_gc at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/safepoint.c:173
jl_set_gc_and_wait at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/julia_internal.h:960 [inlined]
segv_handler at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/signals-unix.c:363 [inlined]
segv_handler at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/signals-unix.c:350
unknown function (ip: 0x7fd3c778704f)
ijl_gc_safepoint at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/jlapi.c:472
unknown function (ip: (nil))
```

I think we can ignore the GC stuff at the top, but a bit further down we seem to be computing an ideal quotient via singular. Shortened backtrace with some intermediate julia frames and long filesystem paths removed:
```
id_Quotient at packages/CxxWrap/I0P2E/src/CxxWrap.jl:676 [inlined]
quotient at packages/Singular/sh9V0/src/ideal/ideal.jl:560
quotient at Oscar.jl/src/Rings/mpoly-ideals.jl:295
#5718 at Oscar.jl/src/AlgebraicGeometry/Schemes/Sheaves/IdealSheaves.jl:877 [inlined]
_minimal_power_such_that at Oscar.jl/src/AlgebraicGeometry/Schemes/Sheaves/IdealSheaves.jl:800
#order_of_vanishing#5715 at Oscar.jl/src/AlgebraicGeometry/Schemes/Sheaves/IdealSheaves.jl:877
order_of_vanishing at Oscar.jl/src/AlgebraicGeometry/Schemes/Sheaves/IdealSheaves.jl:833
#_subsystem#6086 at Oscar.jl/src/AlgebraicGeometry/Schemes/Divisors/WeilDivisor.jl:573
_subsystem at Oscar.jl/src/AlgebraicGeometry/Schemes/Divisors/WeilDivisor.jl:546
subsystem at Oscar.jl/src/AlgebraicGeometry/Schemes/Divisors/WeilDivisor.jl:530
_elliptic_parameter at Oscar.jl/src/AlgebraicGeometry/Surfaces/EllipticSurface/NeighborStep.jl:419
elliptic_parameter at Oscar.jl/src/AlgebraicGeometry/Surfaces/EllipticSurface/NeighborStep.jl:401
```
The linenumbers correspond to the current master (fcd06001bb3f76ba0f3b55f56991a594058d49b0).

<details>
<summary>[1] Backtrace for the (probably unrelated) singular crash:</summary>

https://github.com/oscar-system/Oscar.jl/actions/runs/14019711952/job/39250018524?pr=4504#step:7:451

```
[2024] signal (11.1): Segmentation fault
in expression starting at REPL[69]:1
omInsertBinPage at /workspace/srcdir/Singular/omalloc/om_Alloc.c:110
omAllocBinFromFullPage at /workspace/srcdir/Singular/omalloc/om_Alloc.c:146
_Z6p_ISetlP8ip_sring at /home/runner/.julia/artifacts/8f4444dc1ddba49118238e1595fd22f7047b7c05/lib/libpolys.so (unknown line)
_Z7rGetVariP8ip_sring at /home/runner/.julia/artifacts/8f4444dc1ddba49118238e1595fd22f7047b7c05/lib/libpolys.so (unknown line)
_ZN5jlcxx6detail11CallFunctorIP8spolyrecJiP8ip_sringEE5applyEPKviNS_13WrappedCppPtrE at /home/runner/.julia/artifacts/2af3954532f1b48f0f55af11f99a7f7cc512d3ca/lib/libsingular_julia.so (unknown line)
rGetVar at /home/runner/.julia/packages/CxxWrap/I0P2E/src/CxxWrap.jl:676 [inlined]
#77 at ./none:0 [inlined]
iterate at ./generator.jl:47 [inlined]
collect_to! at ./array.jl:892 [inlined]
collect_to_with_first! at ./array.jl:870 [inlined]
collect at ./array.jl:844
gens at /home/runner/.julia/packages/Singular/sh9V0/src/poly/poly.jl:82 [inlined]
_PolynomialRing at /home/runner/.julia/packages/Singular/sh9V0/src/poly/poly.jl:1600
#polynomial_ring#96 at /home/runner/.julia/packages/Singular/sh9V0/src/poly/poly.jl:1607 [inlined]
polynomial_ring at /home/runner/.julia/packages/Singular/sh9V0/src/poly/poly.jl:1604
unknown function (ip: 0x7f00541bbdee)
_jl_invoke at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:2895 [inlined]
ijl_apply_generic at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:3077
_create_singular_poly_ring at /home/runner/work/Oscar.jl/Oscar.jl/src/Rings/oscar_singular.jl:400
iso_oscar_singular_poly_ring at /home/runner/work/Oscar.jl/Oscar.jl/src/Rings/oscar_singular.jl:417
unknown function (ip: 0x7f00541f5caf)
_jl_invoke at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:2895 [inlined]
ijl_apply_generic at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:3077
singular_generators at /home/runner/work/Oscar.jl/Oscar.jl/src/Rings/mpoly.jl:385
singular_generators at /home/runner/work/Oscar.jl/Oscar.jl/src/Rings/mpoly.jl:668 [inlined]
singular_polynomial_ring at /home/runner/work/Oscar.jl/Oscar.jl/src/Rings/mpoly.jl:672 [inlined]
#ideal_membership#369 at /home/runner/work/Oscar.jl/Oscar.jl/src/Rings/mpoly-ideals.jl:1673
ideal_membership at /home/runner/work/Oscar.jl/Oscar.jl/src/Rings/mpoly-ideals.jl:1672 [inlined]
in at /home/runner/work/Oscar.jl/Oscar.jl/src/Rings/mpoly-ideals.jl:1676
unknown function (ip: 0x7f005403a5c9)
_jl_invoke at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:2895 [inlined]
ijl_apply_generic at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:3077
ideal_membership at /home/runner/work/Oscar.jl/Oscar.jl/src/Rings/mpoly-localizations.jl:1884
in at /home/runner/work/Oscar.jl/Oscar.jl/src/Rings/localization_interface.jl:486 [inlined]
iszero at /home/runner/work/Oscar.jl/Oscar.jl/src/Rings/mpolyquo-localizations.jl:864
is_trivial at /home/runner/.julia/packages/AbstractAlgebra/v3Cp8/src/Rings.jl:213
#7 at /home/runner/.julia/packages/AbstractAlgebra/v3Cp8/src/generic/GenericTypes.jl:351
get_cached! at /home/runner/.julia/packages/AbstractAlgebra/v3Cp8/src/AbstractAlgebra.jl:159 [inlined]
MPolyRing at /home/runner/.julia/packages/AbstractAlgebra/v3Cp8/src/generic/GenericTypes.jl:350 [inlined]
* at /home/runner/.julia/packages/AbstractAlgebra/v3Cp8/src/generic/MPoly.jl:1589
* at /home/runner/work/Oscar.jl/Oscar.jl/src/Rings/mpoly-graded.jl:819 [inlined]
* at /home/runner/.julia/packages/AbstractAlgebra/v3Cp8/src/NCRings.jl:80 [inlined]
* at /home/runner/work/Oscar.jl/Oscar.jl/src/Rings/MPolyQuo.jl:721
evaluate at /home/runner/.julia/packages/AbstractAlgebra/v3Cp8/src/MPoly.jl:909
unknown function (ip: 0x7f005398f999)
_jl_invoke at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:2895 [inlined]
ijl_apply_generic at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:3077
my_dehom at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/ProjectiveSchemes/Objects/Methods.jl:349
_broadcast_getindex_evalf at ./broadcast.jl:709 [inlined]
_broadcast_getindex at ./broadcast.jl:682 [inlined]
getindex at ./broadcast.jl:636 [inlined]
copyto_nonleaf! at ./broadcast.jl:1098
unknown function (ip: 0x7f0053996d9f)
_jl_invoke at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:2895 [inlined]
ijl_apply_generic at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:3077
copy at ./broadcast.jl:950
unknown function (ip: 0x7f005398d685)
_jl_invoke at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:2895 [inlined]
ijl_apply_generic at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:3077
materialize at ./broadcast.jl:903 [inlined]
_compute_gluing at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/CoveredProjectiveScheme/CoveredProjectiveScheme.jl:724
underlying_gluing at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Gluing/LazyGluing/Methods.jl:10
gluing_domains at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Gluing/LazyGluing/Methods.jl:28
unknown function (ip: 0x7f0053[449](https://github.com/oscar-system/Oscar.jl/actions/runs/14019711952/job/39250018524?pr=4504#step:7:453)cd5)
_jl_invoke at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:2895 [inlined]
ijl_apply_generic at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:3077
_compute_domains at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Gluing/LazyGluing/Methods.jl:65
_compute_gluing at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Gluing/LazyGluing/Methods.jl:59
underlying_gluing at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Gluing/LazyGluing/Methods.jl:10
gluing_domains at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Gluing/LazyGluing/Methods.jl:28
unknown function (ip: 0x7f0053449495)
_jl_invoke at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:2895 [inlined]
ijl_apply_generic at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:3077
_compute_gluing at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/CoveredProjectiveScheme/CoveredProjectiveScheme.jl:679
underlying_gluing at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Gluing/LazyGluing/Methods.jl:10
gluing_domains at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Gluing/LazyGluing/Methods.jl:28
unknown function (ip: 0x7f00534498b5)
_jl_invoke at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:2895 [inlined]
ijl_apply_generic at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:3077
_compute_domains at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Gluing/LazyGluing/Methods.jl:65
_compute_gluing at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Gluing/LazyGluing/Methods.jl:59
underlying_gluing at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Gluing/LazyGluing/Methods.jl:10
gluing_domains at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Gluing/LazyGluing/Methods.jl:28
unknown function (ip: 0x7f0053449495)
_jl_invoke at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:2895 [inlined]
ijl_apply_generic at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:3077
_compute_gluing at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/CoveredProjectiveScheme/CoveredProjectiveScheme.jl:679
underlying_gluing at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Gluing/LazyGluing/Methods.jl:10
gluing_domains at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Gluing/LazyGluing/Methods.jl:28
unknown function (ip: 0x7f00534498b5)
_jl_invoke at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:2895 [inlined]
ijl_apply_generic at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:3077
_compute_domains at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Gluing/LazyGluing/Methods.jl:65
_compute_gluing at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Gluing/LazyGluing/Methods.jl:59
underlying_gluing at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Gluing/LazyGluing/Methods.jl:10
gluing_domains at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Gluing/LazyGluing/Methods.jl:28
unknown function (ip: 0x7f0053449495)
_jl_invoke at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:2895 [inlined]
ijl_apply_generic at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:3077
_compute_gluing at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/CoveredProjectiveScheme/CoveredProjectiveScheme.jl:679
underlying_gluing at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Gluing/LazyGluing/Methods.jl:10
gluing_domains at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Gluing/LazyGluing/Methods.jl:28
unknown function (ip: 0x7f00534498b5)
_jl_invoke at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:2895 [inlined]
ijl_apply_generic at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:3077
_compute_domains at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Gluing/LazyGluing/Methods.jl:65
_compute_gluing at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Gluing/LazyGluing/Methods.jl:59
underlying_gluing at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Gluing/LazyGluing/Methods.jl:10
gluing_domains at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Gluing/LazyGluing/Methods.jl:28
unknown function (ip: 0x7f0053449495)
_jl_invoke at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:2895 [inlined]
ijl_apply_generic at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:3077
_compute_gluing at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/CoveredProjectiveScheme/CoveredProjectiveScheme.jl:679
underlying_gluing at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Gluing/LazyGluing/Methods.jl:10
gluing_domains at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Gluing/LazyGluing/Methods.jl:28
unknown function (ip: 0x7f00534498b5)
_jl_invoke at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:2895 [inlined]
ijl_apply_generic at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:3077
_compute_domains at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Gluing/LazyGluing/Methods.jl:65
_compute_gluing at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Gluing/LazyGluing/Methods.jl:59
underlying_gluing at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Gluing/LazyGluing/Methods.jl:10
gluing_domains at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Gluing/LazyGluing/Methods.jl:28
unknown function (ip: 0x7f0053449495)
_jl_invoke at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:2895 [inlined]
ijl_apply_generic at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:3077
_compute_gluing at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/CoveredProjectiveScheme/CoveredProjectiveScheme.jl:679
underlying_gluing at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Gluing/LazyGluing/Methods.jl:10
gluing_domains at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Gluing/LazyGluing/Methods.jl:28
unknown function (ip: 0x7f00534498b5)
_jl_invoke at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:2895 [inlined]
ijl_apply_generic at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:3077
_compute_domains at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Gluing/LazyGluing/Methods.jl:65
_compute_gluing at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Gluing/LazyGluing/Methods.jl:59
underlying_gluing at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Gluing/LazyGluing/Methods.jl:10
gluing_domains at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Gluing/LazyGluing/Methods.jl:28
unknown function (ip: 0x7f0053449495)
_jl_invoke at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:2895 [inlined]
ijl_apply_generic at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:3077
_compute_gluing at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/CoveredProjectiveScheme/CoveredProjectiveScheme.jl:679
underlying_gluing at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Gluing/LazyGluing/Methods.jl:10
gluing_domains at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Gluing/LazyGluing/Methods.jl:28
unknown function (ip: 0x7f00534498b5)
_jl_invoke at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:2895 [inlined]
ijl_apply_generic at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:3077
_compute_domains at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Gluing/LazyGluing/Methods.jl:65
_compute_gluing at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Gluing/LazyGluing/Methods.jl:59
underlying_gluing at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Gluing/LazyGluing/Methods.jl:10
gluing_domains at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Gluing/LazyGluing/Methods.jl:28
unknown function (ip: 0x7f0053449495)
_jl_invoke at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:2895 [inlined]
ijl_apply_generic at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:3077
_compute_gluing at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/CoveredProjectiveScheme/CoveredProjectiveScheme.jl:679
underlying_gluing at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Gluing/LazyGluing/Methods.jl:10
gluing_domains at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Gluing/LazyGluing/Methods.jl:28
unknown function (ip: 0x7f00534498b5)
_jl_invoke at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:2895 [inlined]
ijl_apply_generic at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:3077
_compute_domains at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Gluing/LazyGluing/Methods.jl:65
_compute_gluing at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Gluing/LazyGluing/Methods.jl:59
underlying_gluing at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Gluing/LazyGluing/Methods.jl:10
gluing_domains at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Gluing/LazyGluing/Methods.jl:28
unknown function (ip: 0x7f0053449495)
_jl_invoke at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:2895 [inlined]
ijl_apply_generic at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:3077
_compute_gluing at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/CoveredProjectiveScheme/CoveredProjectiveScheme.jl:679
underlying_gluing at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Gluing/LazyGluing/Methods.jl:10
gluing_domains at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Gluing/LazyGluing/Methods.jl:28
unknown function (ip: 0x7f00534498b5)
_jl_invoke at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:2895 [inlined]
ijl_apply_generic at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:3077
_compute_domains at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Gluing/LazyGluing/Methods.jl:65
_compute_gluing at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Gluing/LazyGluing/Methods.jl:59
underlying_gluing at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Gluing/LazyGluing/Methods.jl:10
gluing_domains at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Gluing/LazyGluing/Methods.jl:28
unknown function (ip: 0x7f0053449495)
_jl_invoke at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:2895 [inlined]
ijl_apply_generic at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:3077
_compute_gluing at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/CoveredProjectiveScheme/CoveredProjectiveScheme.jl:679
underlying_gluing at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Gluing/LazyGluing/Methods.jl:10
gluing_domains at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Gluing/LazyGluing/Methods.jl:28
unknown function (ip: 0x7f00534498b5)
_jl_invoke at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:2895 [inlined]
ijl_apply_generic at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:3077
_compute_domains at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Gluing/LazyGluing/Methods.jl:65
_compute_gluing at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Gluing/LazyGluing/Methods.jl:59
underlying_gluing at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Gluing/LazyGluing/Methods.jl:10
gluing_domains at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Gluing/LazyGluing/Methods.jl:28
unknown function (ip: 0x7f0053449495)
_jl_invoke at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:2895 [inlined]
ijl_apply_generic at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:3077
_compute_gluing at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/CoveredProjectiveScheme/CoveredProjectiveScheme.jl:679
underlying_gluing at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Gluing/LazyGluing/Methods.jl:10
gluing_domains at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Gluing/LazyGluing/Methods.jl:28
unknown function (ip: 0x7f00534498b5)
_jl_invoke at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:2895 [inlined]
ijl_apply_generic at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:3077
_compute_domains at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Gluing/LazyGluing/Methods.jl:65
_compute_gluing at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Gluing/LazyGluing/Methods.jl:59
underlying_gluing at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Gluing/LazyGluing/Methods.jl:10
gluing_domains at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Gluing/LazyGluing/Methods.jl:28
unknown function (ip: 0x7f0053449495)
_jl_invoke at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:2895 [inlined]
ijl_apply_generic at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:3077
_compute_gluing at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/CoveredProjectiveScheme/CoveredProjectiveScheme.jl:679
underlying_gluing at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Gluing/LazyGluing/Methods.jl:10
gluing_domains at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Gluing/LazyGluing/Methods.jl:28
unknown function (ip: 0x7f00534498b5)
_jl_invoke at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:2895 [inlined]
ijl_apply_generic at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:3077
_compute_domains at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Gluing/LazyGluing/Methods.jl:65
_compute_gluing at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Gluing/LazyGluing/Methods.jl:59
underlying_gluing at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Gluing/LazyGluing/Methods.jl:10
gluing_domains at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Gluing/LazyGluing/Methods.jl:28
unknown function (ip: 0x7f0053449495)
_jl_invoke at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:2895 [inlined]
ijl_apply_generic at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:3077
_compute_domains at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Gluing/LazyGluing/Methods.jl:46
_compute_gluing at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Gluing/LazyGluing/Methods.jl:38
underlying_gluing at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Gluing/LazyGluing/Methods.jl:10
gluing_morphisms at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/Gluing/Attributes.jl:27
unknown function (ip: 0x7f00539a14d5)
_jl_invoke at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:2895 [inlined]
ijl_apply_generic at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:3077
move_representative at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/FunctionField/FunctionFields.jl:263
_jl_invoke at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:2895 [inlined]
ijl_apply_generic at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:3077
getindex at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/FunctionField/FunctionFields.jl:317
#5290 at ./none:0 [inlined]
iterate at ./generator.jl:47 [inlined]
collect at ./array.jl:834
unknown function (ip: 0x7f0052fb04b5)
_jl_invoke at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:2895 [inlined]
ijl_apply_generic at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:3077
realization_preview at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/CoveredSchemes/Morphisms/MorphismFromRationalFunctions/Methods.jl:279
complexity at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/CoveredSchemes/Morphisms/MorphismFromRationalFunctions/Methods.jl:651
lt at ./ordering.jl:119
unknown function (ip: 0x7f0052faa3b0)
_jl_invoke at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:2895 [inlined]
ijl_apply_generic at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:3077
_issorted at ./sort.jl:1201
_sort! at ./sort.jl:1123 [inlined]
_sort! at ./sort.jl:730 [inlined]
_sort! at ./sort.jl:681 [inlined]
_sort! at ./sort.jl:752
_sort! at ./sort.jl:697 [inlined]
_sort! at ./sort.jl:636 [inlined]
#sort!#28 at ./sort.jl:1463 [inlined]
sort! at ./sort.jl:1[456](https://github.com/oscar-system/Oscar.jl/actions/runs/14019711952/job/39250018524?pr=4504#step:7:460)
unknown function (ip: 0x7f0052fa9039)
_jl_invoke at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:2895 [inlined]
ijl_apply_generic at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:3077
_try_pullback_cheap at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/CoveredSchemes/Morphisms/MorphismFromRationalFunctions/Methods.jl:654
unknown function (ip: 0x7f0052fa1929)
_jl_invoke at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:2895 [inlined]
ijl_apply_generic at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:3077
pullback at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/CoveredSchemes/Morphisms/MorphismFromRationalFunctions/Methods.jl:615
UniversalPullbackSymbol at /home/runner/work/Oscar.jl/Oscar.jl/experimental/Schemes/src/Auxiliary.jl:41 [inlined]
pullback at /home/runner/work/Oscar.jl/Oscar.jl/src/AlgebraicGeometry/Schemes/CoveredSchemes/Morphisms/MorphismFromRationalFunctions/Methods.jl:845
unknown function (ip: 0x7f0052fa05f9)
_jl_invoke at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:2895 [inlined]
ijl_apply_generic at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:3077
#23 at ./none:0
unknown function (ip: 0x7f0052f9f785)
_jl_invoke at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:2895 [inlined]
ijl_apply_generic at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:3077
iterate at ./generator.jl:47 [inlined]
collect at ./array.jl:834
unknown function (ip: 0x7f0052f9f4e5)
_jl_invoke at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:2895 [inlined]
ijl_apply_generic at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:3077
jl_apply at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/julia.h:1982 [inlined]
do_call at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/interpreter.c:126
eval_value at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/interpreter.c:223
eval_stmt_value at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/interpreter.c:174 [inlined]
eval_body at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/interpreter.c:617
jl_interpret_toplevel_thunk at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/interpreter.c:775
jl_toplevel_eval_flex at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/toplevel.c:934
jl_toplevel_eval_flex at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/toplevel.c:877
jl_toplevel_eval_flex at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/toplevel.c:877
ijl_toplevel_eval_in at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/toplevel.c:985
eval at ./boot.jl:385 [inlined]
eval_user_input at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/usr/share/julia/stdlib/v1.10/REPL/src/REPL.jl:150
repl_backend_loop at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/usr/share/julia/stdlib/v1.10/REPL/src/REPL.jl:246
#start_repl_backend#46 at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/usr/share/julia/stdlib/v1.10/REPL/src/REPL.jl:231
start_repl_backend at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/usr/share/julia/stdlib/v1.10/REPL/src/REPL.jl:228
_jl_invoke at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:2895 [inlined]
ijl_apply_generic at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:3077
#run_repl#59 at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/usr/share/julia/stdlib/v1.10/REPL/src/REPL.jl:389
run_repl at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/usr/share/julia/stdlib/v1.10/REPL/src/REPL.jl:375 [inlined]
run_repl at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/usr/share/julia/stdlib/v1.10/REPL/src/REPL.jl:375 [inlined]
#16 at /home/runner/work/Oscar.jl/Oscar.jl/test/book/test.jl:144
unknown function (ip: 0x7f006[502](https://github.com/oscar-system/Oscar.jl/actions/runs/14019711952/job/39250018524?pr=4504#step:7:506)8412)
_jl_invoke at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:2895 [inlined]
ijl_apply_generic at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/gf.c:3077
jl_apply at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/julia.h:1982 [inlined]
start_task at /cache/build/builder-amdci5-6/julialang/julia-release-1-dot-10/src/task.c:1256
Allocations: 600312097 (Pool: 599937686; Big: 374411); GC: 99
Package Oscar errored during testing (received signal: 11)
```
</details>

**Comment by benlorenz** [comment]
Some more results from my experiments, @HechtiDerLachs:

#### Hang:

It does hang in an ideal quotient, for example this one:

```julia
julia> xK = load("xK.mrdi.txt");

julia> aR = load("aR.mrdi.txt");

julia> quotient(xK,aR)
```
With the files [aR.mrdi.txt](https://github.com/user-attachments/files/19453860/aR.mrdi.txt) [xK.mrdi.txt](https://github.com/user-attachments/files/19453859/xK.mrdi.txt) (where `xK.mrdi.txt` corresponds to some `x+K` in the code below).

This quotient is triggered at the end of `order_of_vanishing` / `_minimal_power_such_that`:
https://github.com/oscar-system/Oscar.jl/blob/fcd06001bb3f76ba0f3b55f56991a594058d49b0/src/AlgebraicGeometry/Schemes/Sheaves/IdealSheaves.jl#L877

#### Stability:

One reason why this only happens in some could be that `order_of_vanishing` relies on the order of the keys of an object cache using an `IdDict`:
https://github.com/oscar-system/Oscar.jl/blob/fcd06001bb3f76ba0f3b55f56991a594058d49b0/src/AlgebraicGeometry/Schemes/Sheaves/IdealSheaves.jl#L849
It will try to choose a minimal one by some order but these `complexity` values seem to be either 2 or 3 for most entries (when running the `vinberg_2.jlcon` book-example). Then the first one with that value is chosen which depends on the `objectid`s (i.e. memory address) of these objects.

But looking at my debug output I am quite sure there is even more randomness (probably outside of `order_of_vanishing` as well).

#### Testing:

I changed the `test_chapter` call in `test/book/test.jl` to just run this one chapter (see [this branch](https://github.com/oscar-system/Oscar.jl/tree/bl/bookhangcheck)), added some debug stuff and then let this run for a while using julia 1.11:
```sh
while [ $? -eq 0 ]; do julia --project=. -t1,1 -e 'using Test,Oscar; Oscar.test_module("test/book/test.jl"; new=false)'; done
```
(On my laptop it usually runs for about 9-12 minutes, if it runs longer it is probably stuck)

One way to get debug output from the booktests (which unfortunately capture stdout and stderr) is to use `jl_safe_print`, e.g:
```julia
ccall(:jl_safe_printf, Cvoid, (Cstring, ), "order_of_vanishing  select $(tmp): $(objectid(U)) -- $(repr(U))\n")
```
I pushed some of my debugging code (some commented) to the brach for #4504.

**Comment by HechtiDerLachs** [comment]
Thanks for the investigations! A few comments:

Randomness in the iteration over keys in a dictionary looks like a plausible cause for these problems. I didn't have this on the radar. The line where the hang finally occurs is also rather critical. `_minimal_power_such_that(p, cond)` is doing the following: Produce an exponent `k` such that `cond(p^k)==true` where `cond` is some expression that can be evaluated on `p^k`. This is done by bisection: First we try with powers `p^1, p^2, p^4, p^8, ...` until `cond(p^k)` returns `true` for the first time, say for `k_top = 2^r`, and then we go down again so as to find the minimal exponent where `cond(p^k) == true`. Of course this has the potential to be very unstable in the sense that with only one step ahead in the "build up phase" of the algorithm, we may cross the boundary between "trivial computation" to "completely impossible Groebner basis computation". In the end, we are computing with powers of ideals here and the example you have extracted suggests to me that some too high power has been reached. 

I'm not so sure how to resolve this. First of all, it is now clear that the ball lays in our yard (meaning the geometry people, in particular me). 

 - Trying to avoid randomness in the iteration over the keys may stabilize the booktests, but does not resolve the general problem.
 - If we were using distributed computation in the form of a "try the first five promising keys on five workers, wait for the first to report a successful result and kill off the rest", we would probably get a more stable and usable code here. But I doubt that this is allowed in the test suite; plus: It also does not resolve the issue in general. If the first five "promising keys" all turn out to be bad, then things will still hang. 
 - We could use another version of `_minimal_power_such_that` which is doing what it does in the dummy incremental way. Or introduce a `kwarg` to set a limit exponent `k_lim` from where onwards things are done incrementally? 

Altogether, I'm afraid, this should be split into two tasks: Number 1 would be to somehow stabilize the tests and number 2 how to make the code a bit more robust for the end user. 

Number 1 could probably be addressed with some brute-force hard coding. Number 2 is more delicate and can probably not be fully achieved in general. In the end, our machine has to rely on some trial and error with the possibility of "error in all cases". It's part of the gamble, unfortunately, but it is our declared goal to push the boundaries for successful gambling here. 

Comments, thoughts? @simonbrandhorst , @afkafkafk13 ?

**Comment by HechtiDerLachs** [comment]
@benlorenz : I made a PR (#4766) to address the problem a bit. Does your preparatory work for the investigation allow you to test it in a loop and see whether it stabilizes at least the booktests? 

Edit: I pushed another commit with debugging code to the PR. If that code is enabled, then it should run the computations once with every possible outcome of the presumably randomized iteration over the keys. For me locally this does not hang now, so this might indeed fix the booktests?

**Comment by benlorenz** [comment]
I will let it run with and without the debug code, I also merged your PR to my hangcheck PR to let it run in our CI.

**Comment by HechtiDerLachs** [comment]
It still seems difficult to reproduce the hangs locally. If I run a modified version of the debug-code which does not use a set bound on iterative search in `_minimal_power_such_that`, then I would expect to also encounter at least one example where the hang is triggered. But that does not happen for me. A problem might be that the state of the various caches is pretty random already earlier on with pretty hard-to-foresee consequences down the road. So running the debug-code might fill the cache differently at step A and then this different state leads to the program proceeding differently in step B so that finally we find a totally different state of the cache at step C. 

What this means to me: We probably have no choice but to run the tests in a loop again and see whether we produce hangs with probability < epsilon with epsilon so small that we can live with it.

**Comment by afkafkafk13** [comment]
split it up into two tasks: indeed, this is the way to go! Stabilizing the tests has priority.

> If we were using distributed computation in the form of a "try the first five promising keys on five workers, wait for the first to report a successful result and kill off the rest", we would probably get a more stable and usable code here. But I doubt that this is allowed in the test suite; plus: It also does not resolve the issue in general. If the first five "promising keys" all turn out to be bad, then things will still hang.
  
This may be good on the long run, in particular, if we have an incremental ideal quotient computation as one of the concurring runners. For the time being, the environment is still not mature enough for this.

> We could use another version of `_minimal_power_such_that` which is doing what it does in the dummy incremental way. Or introduce a `kwarg` to set a limit exponent `k_lim` from where onwards things are done incrementally?

Can we identify which cases are the offending ones and maybe characterize them? I would guess that we have something with a high power and an original polynomial with several monomials and coefficients which are not extremely small. If I understand you correctly, there are good choices at the level of calling minimal_power_such_that, but they might not come up as the first one. So identifying and discarding bad choices (on a higher level) and complaining if we happen to run out of good choices, if necessary, might also be a quick and dirty solution for the test.

**Comment by benlorenz** [comment]
I ran the changes from https://github.com/oscar-system/Oscar.jl/pull/4766 in my test-branch on https://github.com/oscar-system/Oscar.jl/pull/4504 and haven't seen any hangs so far, neither in CI nor locally. (Please ignore the crashes in the CI jobs, these are unrelated)

I did 9 runs with 15 jobs each here: https://github.com/oscar-system/Oscar.jl/actions/runs/14129765603?pr=4504
There was no job killed due to a timeout. Before the change from #4766 this happened something like one or two times for each run.

**Comment by HechtiDerLachs** [comment]
Very good news then, right? 

We can then revert the "debug commit" and merge if you like.

**Comment by benlorenz** [comment]
> Very good news then, right?
> 
> We can then revert the "debug commit" and merge if you like.

Fine with me, yes.

It would still be good to better understand this in the long run but it seems good for stabilizing the tests for now.
