### ISSUE TITLE
Errors on nightly (mostly?) due to new hashing

### ISSUE THREAD

**Issue by benlorenz** [oscar-system/Oscar.jl#4882]
Many of our nightly tests are failing due to changed hashing (https://github.com/JuliaLang/julia/pull/57509).
In many cases this looks like re-ordered `Dict`s and `Set`s but there are several weird things as well:

<details>

```
│ julia> G, chi = Oscar.yamada_example(7, 3);
│ 
│ julia> order(G)
│ 126
│ 
│ julia> schur_index(chi)
│ 3
│ 
│ julia> local_schur_indices(chi)
│ 1-element Vector{Pair{Int64, Int64}}:
│  7 => 3
│ ```
│ 
│ Subexpression:
│ 
│ schur_index(chi)
│ 
│ Evaluated output:
│ 
│ ERROR: KeyError: key 3 not found
│ Stacktrace:
│  [1] getindex
│    @ ./dict.jl:477 [inlined]
│  [2] (::Oscar.var"#2156#2157"{Vector{GapObj}, Dict{Int64, Tuple{Int64, Vector, Int64}}, ZZRingElem, Int64})(i::Int64)
│    @ Oscar ~/software/polymake/julia/Oscar-nightly.jl/src/Groups/schur_index.jl:434
│  [3] _all(f::Oscar.var"#2156#2157"{Vector{GapObj}, Dict{Int64, Tuple{Int64, Vector, Int64}}, ZZRingElem, Int64}, itr::Vector{Int64}, ::Colon)
│    @ Base ./anyall.jl:211
│  [4] all(f::Function, a::Vector{Int64}; dims::Function)
│    @ Base ./reducedim.jl:996
│  [5] local_schur_indices(chi::Oscar.GAPGroupClassFunction; cyclic_defect::Vector{Int64})
│    @ Oscar ~/software/polymake/julia/Oscar-nightly.jl/src/Groups/schur_index.jl:434
│  [6] local_schur_indices
│    @ ~/software/polymake/julia/Oscar-nightly.jl/src/Groups/schur_index.jl:235 [inlined]
│  [7] schur_index(chi::Oscar.GAPGroupClassFunction)
│    @ Oscar ~/software/polymake/julia/Oscar-nightly.jl/src/Groups/group_characters.jl:3433
│  [8] top-level scope
│    @ none:1
│ 
```

</details>

<details>

```diff
  julia> Oscar.randseed!(3371100);
  
  julia> Qx, x = QQ[\"x\"];
  
  julia> K, a = number_field(x^4 + 4*x^2 + 2, \"a\");
  
  julia> b = rand(K, -10:10) # random element with coefficients between -10 and 10
  5*a^3 - 7*a^2 + 8*a - 8
  
  julia> A, mA = automorphism_group(K);
  
  julia> list = [mA(s)(b) for s in A]
  4-element Vector{AbsSimpleNumFieldElem}:
   5*a^3 - 7*a^2 + 8*a - 8
   -7*a^3 + 7*a^2 - 26*a + 20
   -5*a^3 - 7*a^2 - 8*a - 8
   7*a^3 + 7*a^2 + 26*a + 20
  
  julia> X = matrix(QQ, coordinates.(list))
  [-8     8   -7    5]
  [20   -26    7   -7]
  [-8    -8   -7   -5]
  [20    26    7    7]
  
  julia> det(X) != 0
  true
  
  julia> det(matrix(QQ, [coordinates(mA(s)(a)) for s in A]))
  0
  
  julia> V, f = galois_module(K);
  
  julia> OK = ring_of_integers(K);
  
  julia> M = f(OK);
  
  julia> is_free(M)
- false
+ ERROR: KeyError: key 4 not found
+ Stacktrace:
+   [1] getindex
+     @ ./dict.jl:477 [inlined]
+   [2] #262
+     @ ./none:-1 [inlined]
+   [3] iterate
+     @ ./generator.jl:48 [inlined]
+   [4] collect
+     @ ./array.jl:790 [inlined]
+   [5] find_small_group(G::MultTableGroup; DB::Hecke.SmallGroupDB)
+     @ Hecke  Hecke
+   [6] find_small_group(G::MultTableGroup)
+     @ Hecke  Hecke
+   [7] _compute_matrix_algebras_from_reps(A::GroupAlgebra{QQFieldElem, MultTableGroup, MultTableGroupElem}, res::Vector{Tuple{…}})
+     @ Hecke  Hecke
+   [8] #_assert_has_refined_wedderburn_decomposition##0
+     @  Hecke [inlined]
+   [9] get!(default::Hecke.var\"#_assert_has_refined_wedderburn_decomposition##0#_assert_has_refined_wedderburn_decomposition##1\"{…}, h::Dict{…}, key::Symbol)
+     @ Base ./dict.jl:458
+  [10] get_attribute!
+     @  AbstractAlgebra [inlined]
+  [11] _assert_has_refined_wedderburn_decomposition
+     @  Hecke [inlined]
+  [12] _transport_refined_wedderburn_decomposition_forward(h::Hecke.AbsAlgAssMor{…}; is_anti::Bool)
+     @ Hecke  Hecke
+  [13] _transport_refined_wedderburn_decomposition_forward
+     @  Hecke [inlined]
+  [14] product_of_components_with_projection(A::GroupAlgebra{QQFieldElem, MultTableGroup, MultTableGroupElem}, a::Vector{Int64})
+     @ Hecke  Hecke
+  [15] lattice(O::Hecke.AlgAssAbsOrd{GroupAlgebra{…}, ZZRing}, v::Vector{Vector{…}})
+     @ Hecke  Hecke
+  [16] free_lattice(O::Hecke.AlgAssAbsOrd{GroupAlgebra{QQFieldElem, MultTableGroup, MultTableGroupElem}, ZZRing}, r::Int64)
+     @ Hecke  Hecke
+  [17] is_free(L::Hecke.ModAlgAssLat{Hecke.AlgAssAbsOrd{…}, Hecke.ModAlgAss{…}, QQMatrix})
+     @ Hecke  Hecke
+  [18] top-level scope
+     @ REPL[142]:1
+ Some type information was truncated. Use `show(err)` to see complete types.
```

</details>

<details>

```
┌ Error: doctest failure in ../src/Groups/group_characters.jl:1278-1281
│ 
│ ```jldoctest
│ julia> show(character_table("A5") % 2)
│ 2-modular Brauer table of A5
│ ```
│ 
│ Subexpression:
│ 
│ show(character_table("A5") % 2)
│ 
│ Evaluated output:
│ 
│ ERROR: MethodError: no method matching identifier(::Nothing)
│ The function `identifier` exists, but no method is defined for this combination of argument types.
│ 
│ Closest candidates are:
│   identifier(!Matched::Oscar.GAPGroupTableOfMarks)
│    @ Oscar ~/software/polymake/julia/Oscar-nightly.jl/src/Groups/tom.jl:398
│   identifier(!Matched::Oscar.GAPGroupCharacterTable)
│    @ Oscar ~/software/polymake/julia/Oscar-nightly.jl/src/Groups/group_characters.jl:1107
│ 
│ Stacktrace:
│  [1] show(io::IOContext{Base.PipeEndpoint}, tbl::Oscar.GAPGroupCharacterTable)
│    @ Oscar ~/software/polymake/julia/Oscar-nightly.jl/src/Groups/group_characters.jl:715
│  [2] show(x::Oscar.GAPGroupCharacterTable)
│    @ Base ./show.jl:491
│  [3] top-level scope
│    @ none:1
│ 
│ Expected output:
│ 
│ 2-modular Brauer table of A5
```

</details>

I think we should:
- disable testing docs and book for nightly (due to changed order in dicts and sets)
- figure out why quite a bit more is failing, maybe code relying on specific ordering?

I ran this with:
```
julia> versioninfo()
Julia Version 1.13.0-DEV.580
Commit 9f9d3acd973 (2025-05-11 22:12 UTC)
```
which does already include the `BigInt` hashing fix.

The most recent PkgEval doesn't look good either: https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_date/2025-05/11/report.html
> 173 packages failed only on the current version.

----
List of encountered issue and corresponding fixes:

- [x] various `KeyError`s for integer keys. Fixed by https://github.com/Nemocas/Nemo.jl/pull/2077.
- [x] order of gens of `unit_group` and printing changes in ALNUTH tests. Fixed by https://github.com/oscar-system/Oscar.jl/issues/4887
- [x] `Expression: !(is_irreducible(zk(6)))` (https://github.com/oscar-system/Oscar.jl/actions/runs/15117474269/job/42491691930?pr=4900#step:11:2974). The hasing-related difference I could find is the order of factors in https://github.com/oscar-system/Oscar.jl/blob/cc623aad06021417c3e363c8ad11d3e142b288af/src/NumberTheory/NmbThy.jl#L178. @thofma any idea why the code relies that heavily on this order of factors? Fixed by #4903. 
- [x] `ArgumentError: Matrix does not define a morphism of abelian groups` (https://github.com/oscar-system/Oscar.jl/actions/runs/15117474269/job/42491692336?pr=4900#step:11:2471). The crucial difference between 1.11 and nightly is in https://github.com/oscar-system/Oscar.jl/blob/6a69acfdf1302d6e58a6e76cc675114fddd0b9dc/experimental/GModule/src/Cohomology.jl#L1865 where `6` gets factored as `2^1 * 3^1` on 1.11 but as `3^1 * 2^1` on nightly. @fieker do you have an idea what's going on there?  Fixed by #4905 
- [x] `Expression: volume(sd) == (8r) // 12 * (6pq2 + 2 * r * q)` and `Expression: _edge_length_for_test.(faces(sd, 1)) == repeat([4], 18)` (https://github.com/oscar-system/Oscar.jl/actions/runs/15125832782/job/42517587500#step:11:6439). The difference between nightly and 1.11 seems to be the ordering of roots in https://github.com/oscar-system/Oscar.jl/blob/852b6d1a33ed53581040b876a816bb33fac714aa/test/PolyhedralGeometry/scalar_types.jl#L21-L22. See #4906, fix in #4908
- [x] `Expression: [(images(iso, S))[1] for S = sylow_system(G1)] == sylow_system(G2)` (https://github.com/oscar-system/Oscar.jl/actions/runs/15133048148/job/42538529636?pr=4908#step:11:7820). Fixed by https://github.com/oscar-system/Oscar.jl/pull/4910

**Comment by lgoettgens** [comment]
My guess for the key issues (haven't looked into it) is that hashing for BigInt and ZZRingElem maybe no longer coincides (but we expect it to).

**Comment by benlorenz** [comment]
> My guess for the key issues (haven't looked into it) is that hashing for BigInt and ZZRingElem maybe no longer coincides (but we expect it to).

Which is weird since we basically call `Base.hash_integer(data(a), h)` for small values.

**Comment by lgoettgens** [comment]
> My guess for the key issues (haven't looked into it) is that hashing for BigInt and ZZRingElem maybe no longer coincides (but we expect it to).

I checked this, and with just loading `Nemo` in 1.13.0-DEV.580, `hash(17) == hash(ZZ(17))` is `false`, while it is `true` on e.g. 1.11.5.
For ints with more than one limb, hashing of BigInt and ZZRingElem does not coincide even on 1.11.5

**Comment by benlorenz** [comment]
I think `BigInt` is not that important, but lots of code relies on the fact that hashing of `ZZRingElem` did coincide with hashing for `Int64` for small (`__fmpz_is_small`) values.

**Comment by lgoettgens** [comment]
The problem is that in nightly `hash` for Ints is no longer equal to `Base.hash_integer`.
```julia
julia> hash(17, UInt(0))
0x62ddf2660625df43

julia> Base.hash_integer(17, UInt(0))
0x99b7cf1a46643f5a
```

**Comment by lgoettgens** [comment]
I just filed my observations upstream as https://github.com/JuliaLang/julia/issues/58386. 

From a first test, the following patch in Nemo seems to at least fix the observations from above, but I would want to wait for a day or so for reactions to the upstream issue:
```patch
diff --git a/src/flint/fmpz.jl b/src/flint/fmpz.jl
index 3976544b2..f34f00550 100644
--- a/src/flint/fmpz.jl
+++ b/src/flint/fmpz.jl
@@ -171,7 +171,7 @@ end
 end
 
 function _hash_integer(a::Int, h::UInt)
-  __fmpz_is_small(a) && return Base.hash_integer(a, h)
+  __fmpz_is_small(a) && return Base.hash(a, h)
   # view it as a BigInt
   z = unsafe_load(Ptr{BigInt}(unsigned(a) << 2))
   s = z.size  # number of active limbs
 ```

**Comment by fingolfin** [comment]
While I agree that there is something to be fixed in Julia itself, I wonder if we shouldn't apply the `__fmpz_is_small` suggested by @lgoettgens anyway, since it only relies on `Base.hash` (and its *documented* behavior) instead of the undocumented `hash_integer`? I see no downside?

As far as I know, for "large" integers our hash function never agreed with that of BigInt...

There was a push at some point to change that but it was deliberately rejected back then as it was slower and a slow down in hashin of `ZZRingElem` (resp. `fmpz` back then) was deemed unacceptable (see e.g. PR nemocas/Nemo.jl#700 although that is about much much more than the hashing). Given this bug I wonder if it wouldn't be worth a thought to reconsider this? Out of curiosity I measured the relative performance on my MacBook M1.

With Julia 1.10:
```
julia> a = ZZ(12345)^40 ; @b hash($a)
21.019 ns

julia> b = BigInt(a) ; @b hash($b)
38.283 ns
```
This seems like a huge (factor 2) difference at first, but this is a bit misleading as it can look quite different when not used in isolation. For example:
```
julia> va = [ZZ(12345)^i for i in 1:40] ; @b hash($va)
1.097 μs

julia> vb = [BigInt(12345)^i for i in 1:40] ; @b hash($vb)
1.318 μs
```

And current nightly of course has a faster implementation, which narrows the gap further:
```
julia> a = ZZ(12345)^40 ; @b hash($a)
10.328 ns

julia> b = BigInt(a) ; @b hash($b)
15.428 ns
```
and
```
julia> va = [ZZ(12345)^i for i in 1:40] ; @b hash($va)
516.204 ns

julia> vb = [BigInt(12345)^i for i in 1:40] ; @b hash($vb)
645.349 ns
```
which is an amazing speed up; plus it seems Julia is starting to catch up.

**Comment by fieker** [comment]
it wasn't so much the speed of hashing directly, it was the fact that BigInt hashing allocated, and that was unacceptable. At least with the quick test here, it seems to no longer do it.
Weather `hash(1)` should coincide with `hash(ZZ(1))` or has to (given that `1 == ZZ(1)` holds) is a different question. Julia also tried to match with  `hash(1.0)`

**Comment by fingolfin** [comment]
hashing of integers indeed does not allocate since at leas 1.6 (I did not check when this was resolved exactly)

**Comment by adienes** [comment]
with https://github.com/JuliaLang/julia/pull/58440, (on larger inputs, since perf hasn't changed much for small inputs) :

```
julia> va = [ZZ(12345)^i for i in 200:240] ; @b hash($va)
6.438 μs # same as nightly

julia> vb = [BigInt(12345)^i for i in 200:240] ; @b hash($vb)
1.375 μs # nightly is 6.604 μs
```

**Comment by lgoettgens** [comment]
The key errors should be gone now. Next iteration of errors:

- [x] `Expression: !(is_irreducible(zk(6)))` (https://github.com/oscar-system/Oscar.jl/actions/runs/15117474269/job/42491691930?pr=4900#step:11:2974). The hasing-related difference I could find is the order of factors in https://github.com/oscar-system/Oscar.jl/blob/cc623aad06021417c3e363c8ad11d3e142b288af/src/NumberTheory/NmbThy.jl#L178. @thofma any idea why the code relies that heavily on this order of factors? Fixed by #4903. 
- [ ] `ArgumentError: Matrix does not define a morphism of abelian groups` (https://github.com/oscar-system/Oscar.jl/actions/runs/15117474269/job/42491692336?pr=4900#step:11:2471). The crucial difference between 1.11 and nightly is in https://github.com/oscar-system/Oscar.jl/blob/6a69acfdf1302d6e58a6e76cc675114fddd0b9dc/experimental/GModule/src/Cohomology.jl#L1865 where `6` gets factored as `2^1 * 3^1` on 1.11 but as `3^1 * 2^1` on nightly. @fieker do you have an idea what's going on there?

**Comment by thofma** [comment]
First hopefully fixed by https://github.com/oscar-system/Oscar.jl/pull/4903.

**Comment by lgoettgens** [comment]
I checked the whole doctest and booktest nightly log for https://github.com/oscar-system/Oscar.jl/actions/runs/15125832782.

The doctests have only errors left that are due to changed printing of sets and dicts 🎉 . In the booktests, that's also mostly the case, but there are a few examples that rely on an ordering of some sorts of things:

- [ ] `cornerstones/number-theory/sym.jlcon`: https://github.com/oscar-system/Oscar.jl/blob/151d0b21286be8823c9822747a97d7155040bcfc/test/book/cornerstones/number-theory/sym.jlcon#L11-L22 relies on ordering of gens of an automorphism group, leading to changes in output as in https://github.com/oscar-system/Oscar.jl/actions/runs/15125832782/job/42517583218#step:7:1181 cc @fieker @thofma
- [ ] `specialized/decker-schmitt-invariant-theory/cox_ring.jl`: https://github.com/oscar-system/Oscar.jl/blob/1870bfd798c8b2edb3a452b9c543924fb5f09219/test/book/specialized/decker-schmitt-invariant-theory/cox_ring.jlcon#L51 relies on ordering of `gens(B)`, leading to changes as in https://github.com/oscar-system/Oscar.jl/actions/runs/15125832782/job/42517583218#step:7:2667. In particular, the sanity checks in the lines below now fail. cc @wdecker @joschmitt 
EDIT: This is fixed in #4940.

I don't know how this should best be fixed. Maybe @lkastner and @benlorenz can decide on a path forward for these?

**Comment by lgoettgens** [comment]
Nightly has precompilation errors due to something in CxxWrap.jl. Reported upstream as https://github.com/JuliaInterop/CxxWrap.jl/issues/484

**Comment by lgoettgens** [comment]
The number theory book test is still broken. See https://github.com/oscar-system/Oscar.jl/pull/4946#issuecomment-2940245259

**Comment by benlorenz** [comment]
To collect the issues in one place, the new diff for the number theory chapter after #4946 is:
```diff
  julia> phi = m(G(@perm (1, 3)(2, 4)))
  Map
    from number field of degree 4 over QQ
    to number field of degree 4 over QQ
  defined by
-   a -> -1//4*a^3 + 13//4*a
+   a -> -a
  
  julia> phi(a)
- -1//4*a^3 + 13//4*a
+ -a
  
  julia> preimage(m, hom(K, K, -a))
- (1,2)(3,4)
+ (1,3)(2,4)
```
(copied from https://github.com/oscar-system/Oscar.jl/pull/4946#issuecomment-2940245259)

One option would be to do the same as we do for the doctests, i.e., filter all output (at least for some jlcon files).

**Comment by lgoettgens** [comment]
Another option I could think of would be to duplicate the jlcon files with changes, change one of the copies and then decide which of the two copies to test based on the julia version. This way it would be trivial to change the default julia version in the book test in the future as we would just need to drop the old copies.

**Comment by fingolfin** [comment]
Personally I think having two more versions of a `.jlcon` file for different Julia versions would be fine. We need to adapt the book examples on the website for new OSCAR & Julia versions anyway.

**Comment by fingolfin** [comment]
@benlorenz said that his team will take a look at this (once nightly works again, right now libcxxwrap leads to crashes)

**Comment by lgoettgens** [comment]
After https://github.com/oscar-system/Oscar.jl/pull/5044, we are back to the two book test failures from https://github.com/oscar-system/Oscar.jl/issues/4882#issuecomment-2893535038- The current state is:

`invariant-theory/cox_ring.jlcon` (some fallout after https://github.com/oscar-system/Oscar.jl/pull/4940):
```diff
 julia> sort(map(BtoR, gens(B)), by=f->representation_matrix(leading_coefficient(f))[1,1])
  3-element Vector{MPolyDecRingElem{AbsSimpleNumFieldElem, AbstractAlgebra.Generic.MPoly{AbsSimpleNumFieldElem}}}:
   (-z_3 - 1)*x[1]^2 + z_3*x[2]^2 + x[3]^2
   z_3*x[1]^2 + (-z_3 - 1)*x[2]^2 + x[3]^2
   x[1]^2 + x[2]^2 + x[3]^2
  
  julia> f1, f2, f3 = ans;
  
  julia> f1^G(g2) == z_3^(-1)*f1
  true
  
  julia> f2^G(g2) == z_3*f2
  true
  
  julia> f3^G(g2) == f3
  true
  
  julia> grading_group(B)
  Z/3
  
  julia> degree(B[1])
- Abelian group element [2]
+ Abelian group element [1]
  
  julia> degree(B[2])
- Abelian group element [0]
+ Abelian group element [2]
  
  julia> degree(B[3])
- Abelian group element [1]
+ Abelian group element [0]
```

`number_theory/sym.jlcon` (after attempted fix in https://github.com/oscar-system/Oscar.jl/pull/4946):
```diff
julia> G, m = automorphism_group(PermGroup, K); G # we only print G
  Permutation group of degree 4
  
  julia> describe(G)
  \"C2 x C2\"
  
  julia> phi = m(G(@perm (1, 3)(2, 4)))
  Map
    from number field of degree 4 over QQ
    to number field of degree 4 over QQ
  defined by
-   a -> -1//4*a^3 + 13//4*a
+   a -> -a
  
  julia> phi(a)
- -1//4*a^3 + 13//4*a
+ -a
  
  julia> preimage(m, hom(K, K, -a))
- (1,2)(3,4)
+ (1,3)(2,4)
```

@fingolfin since you already tried to fix these two at some point, would you want to give it another go?

**Comment by lgoettgens** [comment]
We had green CI on nightly in the last few days (e.g. https://github.com/oscar-system/Oscar.jl/actions/runs/16689468466), so this seems to be resolved.
